### ISSUE TITLE
個人で使っていたCSSを追加

### ISSUE THREAD

**Issue by kazuemon** [kazuemon/dendai-unipa-extension#1]
```css
@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap');
 html {
    min-height: 100%;
}
*:not(.fa) {
    font-family:'IBM Plex Sans JP', sans-serif !important;
    line-height: 1.4;
}
.fontBold {
    font-weight: 700;
    color: #111;
}
body {
    margin-bottom: 0px;
    min-width: auto;
    min-height: 100%;
    font-weight: 400;
    color: #333;
}
a, label, input, textArea {
    font-family:'Noto Sans JP', sans-serif !important;
}
.infoMain {
    display:none;
}
#funcContent {
    width: 100% !important;
}
.classTable {
    width: auto;
}
.headerYobi:last-of-type, .colYobi:last-of-type {
    display:none;
}
. div[data-widget="widget_funcForm_tabArea"] {
    border: none !important;
}
div[data-widget="widget_funcForm_tabArea"] .ui-tabs-panels > div {
    padding: 1em 0;
}
.ui-accordion-header {
    background-color: #ebebeb !important;
}
.ui-accordion-content {
    background-color: #fff !important;
}
.loginForm {
    max-width: 300px;
    margin: 0 auto;
    background-color: #ffffff;
    color: #333;
    border: none;
}
#login {
    width: 100%;
    min-width: unset;
    max-width: unset;
    padding: 50px 0 0 0;
    display: flex;
    justify-content: center;
    align-items: center;
}
#loginForm\:loginButton {
    width: 100%;
}
#wrap {
    display: grid;
    grid-template-columns: 250px 1fr;
}
#headerForm {
    grid-column: 1 / 3;
    grid-row: 1/2;
}
#mainMenu {
    background-color: #fff;
    grid-column: 1 / 2;
    grid-row: 2 / 5;
    margin: 0;
}
.ui-tabs-nav {
    display: flex;
    flex-wrap: wrap;
    gap: 4px;
    background-color: unset;
    padding: 1em 1.4em 0 1.4em !important;
}
.ui-tabs-nav li {
    border-bottom: none;
    top: unset;
    margin: 0;
    border: 0 !important;
    background-color: #ebebeb !important;
    border-radius: 16px;
    transition: all 0.3s ease;
}
.ui-tabs-outline {
    outline: none !important;
}
.ui-tabs-nav li a {
    transition: all 0.3s ease;
    color: #333 !important;
}
.ui-tabs-nav li.ui-state-active, .ui-tabs-nav li.ui-state-hover {
    background-color: #004EA2 !important;
}
.ui-tabs-nav li.ui-state-active a, .ui-tabs-nav li.ui-state-hover a {
    color: #fff !important;
}
.textOf {
    white-space: normal;
}
.keiji {
    width: auto;
    margin: 0;
}
.keiji a {
    display: block;
    text-decoration: none;
    font-size: 1.1em !important;
}
.ui-scrollpanel[id*="funcForm:tabArea"] .alignRight {
    padding: 20px;
    background-color: #f2f2f2;
    border-radius: 10px;
    display: flex;
    align-items: center;
    flex-wrap: wrap;
}
.ui-scrollpanel[id*="funcForm:tabArea"] .alignRight .inlineBlock {
    margin-left: auto;
}
.ui-scrollpanel[id*="funcForm:tabArea"] .alignRight .inlineBlock .ui-button {
    width: 40px;
    height: 40px;
    min-width: unset !important;
    display: inline-flex;
    justify-content: center;
    align-items: center;
}
.ui-scrollpanel[id*="funcForm:tabArea"] .alignRight .inlineBlock .ui-button .ui-button-icon-left {
    position: static;
    top: unset;
    margin-top: 0;
}
.ui-scrollpanel[id*="funcForm:tabArea"] .alignRight .inlineBlock .ui-button .ui-icon-close {
    background-position: -64px -144px;
    background-image: url("/uprx/javax.faces.resource/images/ui-icons_808080_256x240.png.xhtml?ln=primefaces-basic");
}
.ui-scrollpanel[id*="funcForm:tabArea"] .alignRight .inlineBlock .ui-button .ui-button-text {
    display: none;
}
.hiddenStyle, .hiddenStyle * {
    display: none;
}
.ui-scrollpanel[id*="funcForm:tabArea"] .alignRight:not(.ui-scrollpanel[id*="funcForm:tabArea:0:j_idt232:"] .alignRight:first-of-type) {
    margin-top: 20px;
}
hr[id*="funcForm:tabArea"] {
    display: none;
}
/*

	Menu

*/
 .ui-menu-list {
    display: flex;
    flex-flow: column;
    max-width: 220px;
    margin: 0 auto;
}
.ui-menu.ui-widget-content {
    border: none;
    background: none;
}
.ui-menubar .ui-menuitem {
    display: inline-block;
    width: 100%;
    height: 100%;
}
.ui-menubar .ui-menuitem-link {
    box-sizing: border-box;
    width: 100%;
    height: 100%;
    padding: 0.8em 0.5em;
}
.ui-menuitem-text {
    display: inline-block;
    margin: auto 0;
    float: none;
}
#transitionArea {
    height: 0;
}
#mainWrapTop {
    grid-column: 2 / 3;
    grid-row: 2/3;
}
#messageDialogArea {
    grid-column: 2 / 3;
    grid-row: 3/4;
}
#mainWrapBottom {
    grid-column: 2 / 3;
    grid-row: 4/5;
}
.footerArea {
    grid-column: 1/3;
    max-width: 100%;
}
.cf {
    margin: 0;
    position: static;
    min-width: unset;
}
/*
		Replace Modal
*/
 .ui-menu .ui-menu-parent .ui-menu-child {
    position: static !important;
    background-color: transparent;
    box-shadow: none;
    padding: 0;
}
.ui-menubar .ui-menuitem {
    height: auto;
}
.ui-menu.ui-megamenu .ui-menu-child .ui-menu-list {
    width: 100%;
}
.ui-menubar .ui-menu-child .ui-menuitem-link {
    width: 100%;
}
.ui-menu-list .ui-widget-header {
    clear: none;
    width: 100%;
    margin: 0 !important;
    float: none;
    background-color: #ccdee6;
    color: #005882;
    border: none;
}
.ui-menu-list .ui-widget-header h3 {
    padding: 0.8em 0.5em;
}
.ui-megamenu td {
    display: block;
}
.ui-menu.ui-megamenu .ui-menu-child > table {
    width: 100%;
}
.ui-menu-list .ui-widget-content {
    border: none;
}
.ui-menu .ui-menuitem-text {
    font-weight: bold;
}
.ui-menu .ui-menu-child .ui-menuitem-text {
    font-weight: normal;
}
```

```css
/*
		Replace Loading
        ref: https://github.com/nzbin/three-dots
*/
 .ui-blockui-content {
    content:'';
    position: relative;
    padding: 0;
    width: 10px;
    height: 10px;
    border-radius: 5px;
    background-color: transparent;
    color: transparent !important;
    box-shadow: 0 -18px 0 0 #164F9E, 12.72984px -12.72984px 0 0 #164F9E, 18px 0 0 0 #164F9E, 12.72984px 12.72984px 0 0 rgba(22, 79, 158, 0), 0 18px 0 0 rgba(22, 79, 158, 0), -12.72984px 12.72984px 0 0 rgba(22, 79, 158, 0), -18px 0 0 0 rgba(22, 79, 158, 0), -12.72984px -12.72984px 0 0 rgba(22, 79, 158, 0);
    -webkit-animation: dot-spin 1.5s infinite linear;
    animation: dot-spin 1.5s infinite linear;
    background: none;
}
.ui-blockui-content img {
    display: none;
}
.ui-blockui-content.ui-widget-content {
    border: none !important;
    background: none !important;
    color: transparent !important;
}
.ui-widget-overlay {
    background: rgba(0, 0, 0, 0.5);
    opacity: 1;
}
@-webkit-keyframes dot-spin {
    0%, 100% {
        box-shadow: 0 -18px 0 0 #164F9E, 12.72984px -12.72984px 0 0 #164F9E, 18px 0 0 0 #164F9E, 12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), 0 18px 0 -5px rgba(22, 79, 158, 0), -12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), -18px 0 0 -5px rgba(22, 79, 158, 0), -12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0);
    }
    12.5% {
        box-shadow: 0 -18px 0 -5px rgba(22, 79, 158, 0), 12.72984px -12.72984px 0 0 #164F9E, 18px 0 0 0 #164F9E, 12.72984px 12.72984px 0 0 #164F9E, 0 18px 0 -5px rgba(22, 79, 158, 0), -12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), -18px 0 0 -5px rgba(22, 79, 158, 0), -12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0);
    }
    25% {
        box-shadow: 0 -18px 0 -5px rgba(22, 79, 158, 0), 12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0), 18px 0 0 0 #164F9E, 12.72984px 12.72984px 0 0 #164F9E, 0 18px 0 0 #164F9E, -12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), -18px 0 0 -5px rgba(22, 79, 158, 0), -12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0);
    }
    37.5% {
        box-shadow: 0 -18px 0 -5px rgba(22, 79, 158, 0), 12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0), 18px 0 0 -5px rgba(22, 79, 158, 0), 12.72984px 12.72984px 0 0 #164F9E, 0 18px 0 0 #164F9E, -12.72984px 12.72984px 0 0 #164F9E, -18px 0 0 -5px rgba(22, 79, 158, 0), -12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0);
    }
    50% {
        box-shadow: 0 -18px 0 -5px rgba(22, 79, 158, 0), 12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0), 18px 0 0 -5px rgba(22, 79, 158, 0), 12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), 0 18px 0 0 #164F9E, -12.72984px 12.72984px 0 0 #164F9E, -18px 0 0 0 #164F9E, -12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0);
    }
    62.5% {
        box-shadow: 0 -18px 0 -5px rgba(22, 79, 158, 0), 12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0), 18px 0 0 -5px rgba(22, 79, 158, 0), 12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), 0 18px 0 -5px rgba(22, 79, 158, 0), -12.72984px 12.72984px 0 0 #164F9E, -18px 0 0 0 #164F9E, -12.72984px -12.72984px 0 0 #164F9E;
    }
    75% {
        box-shadow: 0 -18px 0 0 #164F9E, 12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0), 18px 0 0 -5px rgba(22, 79, 158, 0), 12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), 0 18px 0 -5px rgba(22, 79, 158, 0), -12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), -18px 0 0 0 #164F9E, -12.72984px -12.72984px 0 0 #164F9E;
    }
    87.5% {
        box-shadow: 0 -18px 0 0 #164F9E, 12.72984px -12.72984px 0 0 #164F9E, 18px 0 0 -5px rgba(22, 79, 158, 0), 12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), 0 18px 0 -5px rgba(22, 79, 158, 0), -12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), -18px 0 0 -5px rgba(22, 79, 158, 0), -12.72984px -12.72984px 0 0 #164F9E;
    }
}
@keyframes dot-spin {
    0%, 100% {
        box-shadow: 0 -18px 0 0 #164F9E, 12.72984px -12.72984px 0 0 #164F9E, 18px 0 0 0 #164F9E, 12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), 0 18px 0 -5px rgba(22, 79, 158, 0), -12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), -18px 0 0 -5px rgba(22, 79, 158, 0), -12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0);
    }
    12.5% {
        box-shadow: 0 -18px 0 -5px rgba(22, 79, 158, 0), 12.72984px -12.72984px 0 0 #164F9E, 18px 0 0 0 #164F9E, 12.72984px 12.72984px 0 0 #164F9E, 0 18px 0 -5px rgba(22, 79, 158, 0), -12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), -18px 0 0 -5px rgba(22, 79, 158, 0), -12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0);
    }
    25% {
        box-shadow: 0 -18px 0 -5px rgba(22, 79, 158, 0), 12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0), 18px 0 0 0 #164F9E, 12.72984px 12.72984px 0 0 #164F9E, 0 18px 0 0 #164F9E, -12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), -18px 0 0 -5px rgba(22, 79, 158, 0), -12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0);
    }
    37.5% {
        box-shadow: 0 -18px 0 -5px rgba(22, 79, 158, 0), 12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0), 18px 0 0 -5px rgba(22, 79, 158, 0), 12.72984px 12.72984px 0 0 #164F9E, 0 18px 0 0 #164F9E, -12.72984px 12.72984px 0 0 #164F9E, -18px 0 0 -5px rgba(22, 79, 158, 0), -12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0);
    }
    50% {
        box-shadow: 0 -18px 0 -5px rgba(22, 79, 158, 0), 12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0), 18px 0 0 -5px rgba(22, 79, 158, 0), 12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), 0 18px 0 0 #164F9E, -12.72984px 12.72984px 0 0 #164F9E, -18px 0 0 0 #164F9E, -12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0);
    }
    62.5% {
        box-shadow: 0 -18px 0 -5px rgba(22, 79, 158, 0), 12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0), 18px 0 0 -5px rgba(22, 79, 158, 0), 12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), 0 18px 0 -5px rgba(22, 79, 158, 0), -12.72984px 12.72984px 0 0 #164F9E, -18px 0 0 0 #164F9E, -12.72984px -12.72984px 0 0 #164F9E;
    }
    75% {
        box-shadow: 0 -18px 0 0 #164F9E, 12.72984px -12.72984px 0 -5px rgba(22, 79, 158, 0), 18px 0 0 -5px rgba(22, 79, 158, 0), 12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), 0 18px 0 -5px rgba(22, 79, 158, 0), -12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), -18px 0 0 0 #164F9E, -12.72984px -12.72984px 0 0 #164F9E;
    }
    87.5% {
        box-shadow: 0 -18px 0 0 #164F9E, 12.72984px -12.72984px 0 0 #164F9E, 18px 0 0 -5px rgba(22, 79, 158, 0), 12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), 0 18px 0 -5px rgba(22, 79, 158, 0), -12.72984px 12.72984px 0 -5px rgba(22, 79, 158, 0), -18px 0 0 -5px rgba(22, 79, 158, 0), -12.72984px -12.72984px 0 0 #164F9E;
    }
}
```
